### ISSUE TITLE
Review and decide on the behaviour of PulseSigmoid

### ISSUE THREAD

**Issue by pausz** [BrainDynamicsUSYD/nftsim#156]
For a PulseSigmoid with `Width` = time step and `Amplitude` = 1, we obtain the following profile:

![screenshot from 2018-02-15 14-43-03](https://user-images.githubusercontent.com/1563810/36239544-353b22f2-1256-11e8-87e0-fd41e3a5ab3b.png)

At first sight it might seem counter-intuitive to set up  an amplitude of 1, and obtain an amplitude of approx 0.25. This is due to the nature of the PulseSigmoid, which is essentially a difference of two sigmoid functions. If the parameter `Sigma` is not correctly set then the amplitude of PulseSigmoid will not correspond to the amplitude of PulseRect. 

How to set the right parameters: generally `Sigma` should decrease as `Width` decreases, so the maximum amplitude of PulseSigmoid is closer to `Amplitude`, but there won't be a one to one correspondence, in particular as the width of the PulseSigmoid approaches the time step.

**Comment by pausz** [comment]
This issues is fixed by #170. 

Time: 12 Deltat: 9.765625e-04
Nodes: 144

    Connection matrix:
From:  1
To 1:  0

```
Population 1: Stimulation
Length: 0.5
 Stimulus: Superimpose: 2
 Stimulus: PulseRect - Onset: 2 Node: 62 Amplitude: 1.0 Width: 1.0 Period: 3 Pulses: 3
 Stimulus: PulseSigmoid - Onset: 2 Node: 42 Amplitude: 1.0 Width: 0.1 Period: 3 Pulses: 3

Output: Node: 33 42 62 77 Start: 0
Population: 1
Dendrite:
Propagator:
Coupling:
```

![screenshot from 2018-06-07 15-56-48](https://user-images.githubusercontent.com/1563810/41080798-7195d6a8-6a6b-11e8-8ae5-c897cef64365.png)


Notice that if one specifies Sigma, this will preven NFTsim from adapting its value

Time: 12 Deltat: 9.765625e-04
Nodes: 144

    Connection matrix:
From:  1
To 1:  0

```
Population 1: Stimulation
Length: 0.5
 Stimulus: Superimpose: 2
 Stimulus: PulseRect - Onset: 2 Node: 62 Amplitude: 1.0 Width: 1.0 Period: 3 Pulses: 3
 Stimulus: PulseSigmoid - Onset: 2 Node: 42 Amplitude: 1.0 Width: 0.1 Period: 3 Pulses: 3 Sigma: 0.0325

Output: Node: 33 42 62 77 Start: 0
Population: 1
Dendrite:
Propagator:
Coupling:
```

and we will obtain 
![screenshot from 2018-06-07 15-59-37](https://user-images.githubusercontent.com/1563810/41080879-dbc6cf82-6a6b-11e8-9910-ae10dc66760a.png)
